kind: pipeline
name: default

steps:
  - name: test
    image: golang:1.17-alpine
    environment:
      CGO_ENABLED: 0
    commands:
      - "until nc -z mqtt 1883; do sleep 1; done"
      - go build -mod=vendor -o spacestatus .
      - go test -mod=vendor ./...
      - tar cvpzf spacestatus.tgz spacestatus templates static

  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - spacestatus.tgz
      checksum:
        - md5
        - sha1
        - sha256
    when:
      event: tag

services:
  - name: mqtt
    image: eclipse-mosquitto:1.6
